# NOTE: This docker-compose.yml is now OPTIONAL
# The Minecraft mod can start n8n containers directly via DockerManager
# This file remains for manual testing and development

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: auton8-n8n
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - N8N_HOST=${N8N_HOST}
      - N8N_PORT=${N8N_PORT}
      - N8N_EDITOR_BASE_URL=${N8N_EDITOR_BASE_URL}
      - N8N_PROTOCOL=http
      - GENERIC_TIMEZONE=${TZ}
      # Local file storage (sqlite)
      - DB_TYPE=sqlite
      - DB_SQLITE_VACUUM_ON_STARTUP=true
      # Minescript API configuration
      - N8N_CUSTOM_EXTENSIONS=/home/node/.n8n/custom
      - MINESCRIPT_API_ENABLED=true
      - MINESCRIPT_API_PORT=5679
      - MINESCRIPT_AUTH_REQUIRED=true
    volumes:
      - ./n8n/.n8n:/home/node/.n8n
    ports:
      - "127.0.0.1:5678:5678"
      - "127.0.0.1:5679:5679"
